# Anexando dados
Primeiro, importe os pacotes necessários e carregue os arquivos `winequality-red.csv` e `winequality-white.csv`.

In [41]:
# importe o numpy e o pandas
import pandas as pd
import numpy as np

# carregue os conjuntos de dados de vinhos tintos e brancos
red_df = pd.read_csv('winequality-red.csv', sep=';')
white_df = pd.read_csv('winequality-white.csv', sep=';')

## Crie colunas de cor
Crie dois vetores de tamanho igual ao número de linhas nos dataframes tinto e branco que repetem o valor “red” or “white”. O NumPy oferece uma forma bem fácil de fazer isso. Aqui está a documentação para a função [repeat do NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html). Dê uma olhada e tente você mesmo.

In [50]:
# crie vetor de cor para o dataframe tinto
color_red = np.repeat('Red', len(red_df))

# crie vetor de cor para o dataframe branco
color_white = np.repeat('White', len(white_df))

Adicione os vetores de cor aos dataframes tinto e branco. Faça isso associando uma nova coluna chamada 'color' ao vetor apropriado. A célula abaixo faz isso para o dataframe tinto.

In [43]:
red_df['color'] = color_red
red_df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur-dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red

Faça o mesmo para o dataframe branco e use `head()` para confirmar a mudança.

In [51]:
white_df['color'] = color_white
white_df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,White
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,White
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,White
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,White
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,White

## Combine dataframes com append
Veja a documentação para a função [append do Pandas](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.append.html) e veja se você pode usar isso para descobrir como combinar os dataframes. (Bonus: Por que não estamos usando o método [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) para combinar dataframes?) Se você não entender, vou te mostrar como mais tarde. Certifique-se de salvar seu trabalho neste notebook! Você irá voltar para isso mais tarde.

In [52]:
# anexe dataframes

red_df = red_df.rename(columns={'total_sulfur-dioxide': 'total_sulfur_dioxide'})

wine_df = red_df.append(white_df, sort=False)

# exiba o dataframe para ver se tudo deu certo
wine_df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,Red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,Red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,Red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,Red

## Salve o dataset combinado
Salve seu dataframe recém-combinado como `winequality_edited.csv`. Lembre-se de configurar `index=False` para evitar salvar com uma coluna não-nomeada!

In [54]:
wine_df.to_csv('wine.csv')

In [55]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6497 entries, 0 to 4897
Data columns (total 13 columns):
fixed_acidity           6497 non-null float64
volatile_acidity        6497 non-null float64
citric_acid             6497 non-null float64
residual_sugar          6497 non-null float64
chlorides               6497 non-null float64
free_sulfur_dioxide     6497 non-null float64
total_sulfur_dioxide    6497 non-null float64
density                 6497 non-null float64
pH                      6497 non-null float64
sulphates               6497 non-null float64
alcohol                 6497 non-null float64
quality                 6497 non-null int64
color                   6497 non-null object
dtypes: float64(11), int64(1), object(1)
memory usage: 710.6+ KB